// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYI0GVl3lNY1n0O-6KjcHBptl6d_xMyr4',
    appId: '1:50554413477:web:4c73769cb4c9830662884c',
    messagingSenderId: '50554413477',
    projectId: 'balafire-31657',
    authDomain: 'balafire-31657.firebaseapp.com',
    databaseURL: 'https://balafire-31657.firebaseio.com',
    storageBucket: 'balafire-31657.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWnYD2sciR68eSuM6M-W1FdAYXwQNsIo',
    appId: '1:50554413477:android:b5ed6f77b6d7188a62884c',
    messagingSenderId: '50554413477',
    projectId: 'balafire-31657',
    databaseURL: 'https://balafire-31657.firebaseio.com',
    storageBucket: 'balafire-31657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAOXafmLB2rzjXgFZyQSPJHGSWIemeQE',
    appId: '1:50554413477:ios:2953ba6d354b201162884c',
    messagingSenderId: '50554413477',
    projectId: 'balafire-31657',
    databaseURL: 'https://balafire-31657.firebaseio.com',
    storageBucket: 'balafire-31657.appspot.com',
    androidClientId: '50554413477-67c5tqiek4ei9rej4jvgn8ub877nbg5d.apps.googleusercontent.com',
    iosClientId: '50554413477-pghqqhd123bdau1k6j556le56cap9cff.apps.googleusercontent.com',
    iosBundleId: 'com.example.negup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAOXafmLB2rzjXgFZyQSPJHGSWIemeQE',
    appId: '1:50554413477:ios:2953ba6d354b201162884c',
    messagingSenderId: '50554413477',
    projectId: 'balafire-31657',
    databaseURL: 'https://balafire-31657.firebaseio.com',
    storageBucket: 'balafire-31657.appspot.com',
    androidClientId: '50554413477-67c5tqiek4ei9rej4jvgn8ub877nbg5d.apps.googleusercontent.com',
    iosClientId: '50554413477-pghqqhd123bdau1k6j556le56cap9cff.apps.googleusercontent.com',
    iosBundleId: 'com.example.negup',
  );
}
